{% set name = "monotonicnetworks" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/monotonicnetworks-{{ version }}.tar.gz
  sha256: 5bf2a188f2272f0fd8113ddc91da457d140ddfd1a145917136deb536113017af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pytorch >=1.8

test:
  imports:
    - monotonicnetworks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/niklasnolte/MonotoneNorm/tree/main
  summary: Pytorch implementation of constrained weight operator norms for robustness and monotonicity in neural networks.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - okitouni
